--- 
abstract: Nifty XUL apps in a XUL::App
author: Agent Zhang <agentzh@yahoo.cn>
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XUL-App
no_index: 
  directory: 
    - doc
    - examples
    - share
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0.30
  Class::Data::Inheritable: 0.06
  File::Copy::Recursive: 0.35
  File::ShareDir: 0.04
  File::Slurp: 0
  Template::Declare: 0.27
  perl: 5.6.1
version: 0.01
